-- NOVA AI Database Schema
-- PostgreSQL Schema Definition

-- Enable UUID extension (REMOVED for compatibility)

-- Users Table
create table users (
   id              number generated by default as identity primary key,
   email           varchar2(255 char) unique not null,
   username        varchar2(100 char) unique not null,
   hashed_password varchar2(255 char) not null,
   full_name       varchar2(255 char),
   is_active       number(1) default 1 not null,
   is_verified     number(1) default 0 not null,
   created_at      timestamp default systimestamp not null,
   updated_at      timestamp default systimestamp not null,
   constraint users_is_active_bool check ( is_active in ( 0,
                                                          1 ) ),
   constraint users_is_verified_bool check ( is_verified in ( 0,
                                                              1 ) ),
   constraint email_format check ( regexp_like ( email,
                                                 '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,}$' ) )
);

-- Create index for faster lookups
create index idx_users_email on
   users (
      email
   );
create index idx_users_username on
   users (
      username
   );

-- Conversations Table
create table conversations (
   id         number generated by default as identity primary key,
   user_id    number not null
      references users ( id )
         on delete cascade,
   title      varchar2(500 char) default 'New Chat',
   created_at timestamp default systimestamp,
   updated_at timestamp default systimestamp
);

create index idx_conversations_user_id on
   conversations (
      user_id
   );
create index idx_conversations_updated_at on
   conversations (
      updated_at
   desc );

-- Messages Table
create table messages (
   id              number generated by default as identity primary key,
   conversation_id number not null
      references conversations ( id )
         on delete cascade,
   role            varchar2(50 char) not null check ( role in ( 'user',
                                                     'assistant',
                                                     'system' ) ),
   content         clob not null,
   metadata        json default '{}',
   created_at      timestamp default systimestamp
);

create index idx_messages_conversation_id on
   messages (
      conversation_id
   );
create index idx_messages_created_at on
   messages (
      created_at
   );

-- Documents Table
create table documents (
   id           number generated by default as identity primary key,
   user_id      number not null
      references users ( id )
         on delete cascade,
   filename     varchar2(255 char) not null,
   file_path    varchar2(500 char) not null,
   file_type    varchar2(50 char) not null,
   file_size    number not null,
   text_content clob,
   summary      clob,
   is_processed number(1) default 0,
   created_at   timestamp default systimestamp,
   updated_at   timestamp default systimestamp,
   constraint documents_is_processed_bool check ( is_processed in ( 0,
                                                                    1 ) )
);

create index idx_documents_user_id on
   documents (
      user_id
   );
create index idx_documents_created_at on
   documents (
      created_at
   desc );

-- Learning Progress Table
create table learning_progress (
   id              number generated by default as identity primary key,
   user_id         number not null
      references users ( id )
         on delete cascade,
   topic           varchar2(255 char) not null,
   roadmap         json default '{}',
   completed_items json default '[]',
   current_level   varchar2(50 char) default 'beginner' check ( current_level in ( 'beginner',
                                                                                 'intermediate',
                                                                                 'advanced' ) ),
   notes           clob,
   is_active       number(1) default 1,
   created_at      timestamp default systimestamp,
   updated_at      timestamp default systimestamp,
   constraint learning_progress_is_active_bool check ( is_active in ( 0,
                                                                      1 ) )
);

create index idx_learning_progress_user_id on
   learning_progress (
      user_id
   );
create index idx_learning_progress_topic on
   learning_progress (
      topic
   );

-- Triggers for updated_at
create or replace trigger update_users_updated_at before
   update on users
   for each row
begin
   :new.updated_at := systimestamp;
end;
/

create or replace trigger update_conversations_updated_at before
   update on conversations
   for each row
begin
   :new.updated_at := systimestamp;
end;
/

create or replace trigger update_documents_updated_at before
   update on documents
   for each row
begin
   :new.updated_at := systimestamp;
end;
/

create or replace trigger update_learning_progress_updated_at before
   update on learning_progress
   for each row
begin
   :new.updated_at := systimestamp;
end;
/

-- Sample Data (Optional - for testing)

-- Insert a test user (password is 'password123' hashed with bcrypt)
insert into users (
   email,
   username,
   hashed_password,
   full_name
) values ( 'test@example.com',
           'testuser',
           '$2b$12$LQv3c1yqBWVHxkd0LHAkCOYz6TtxMQJqhN8/LewY5GyYqOqMgYQAK',
           'Test User' );

-- Comments for documentation
comment on table users is
   'Stores user account information';
comment on table conversations is
   'Stores chat conversation metadata';
comment on table messages is
   'Stores individual chat messages';
comment on table documents is
   'Stores uploaded document information';
comment on table learning_progress is
   'Stores user learning progress and roadmaps';

-- Grant permissions (adjust username as needed)
grant all privileges on users to nova_user;
grant all privileges on conversations to nova_user;
grant all privileges on messages to nova_user;
grant all privileges on documents to nova_user;
grant all privileges on learning_progress to nova_user;