-- NOVA AI Database Schema
-- PostgreSQL Schema Definition

-- Enable UUID extension (REMOVED for compatibility)

-- Users Table
CREATE TABLE users (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR2(255 CHAR) UNIQUE NOT NULL,
    username VARCHAR2(100 CHAR) UNIQUE NOT NULL,
    hashed_password VARCHAR2(255 CHAR) NOT NULL,
    full_name VARCHAR2(255 CHAR),
    is_active NUMBER(1) DEFAULT 1 NOT NULL,
    is_verified NUMBER(1) DEFAULT 0 NOT NULL,
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT users_is_active_bool CHECK (is_active IN (0, 1)),
    CONSTRAINT users_is_verified_bool CHECK (is_verified IN (0, 1)),
    CONSTRAINT email_format CHECK (REGEXP_LIKE(email, '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,}$'))
);

-- Create index for faster lookups
CREATE INDEX idx_users_email ON users(email);
CREATE INDEX idx_users_username ON users(username);

-- Conversations Table
CREATE TABLE conversations (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    title VARCHAR2(500 CHAR) DEFAULT 'New Chat',
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP,
    updated_at TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE INDEX idx_conversations_user_id ON conversations(user_id);
CREATE INDEX idx_conversations_updated_at ON conversations(updated_at DESC);

-- Messages Table
CREATE TABLE messages (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_id NUMBER NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,
    role VARCHAR2(50 CHAR) NOT NULL CHECK (role IN ('user', 'assistant', 'system')),
    content CLOB NOT NULL,
    metadata JSON DEFAULT '{}',
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE INDEX idx_messages_conversation_id ON messages(conversation_id);
CREATE INDEX idx_messages_created_at ON messages(created_at);

-- Documents Table
CREATE TABLE documents (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    filename VARCHAR2(255 CHAR) NOT NULL,
    file_path VARCHAR2(500 CHAR) NOT NULL,
    file_type VARCHAR2(50 CHAR) NOT NULL,
    file_size NUMBER NOT NULL,
    text_content CLOB,
    summary CLOB,
    is_processed NUMBER(1) DEFAULT 0,
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP,
    updated_at TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT documents_is_processed_bool CHECK (is_processed IN (0, 1))
);

CREATE INDEX idx_documents_user_id ON documents(user_id);
CREATE INDEX idx_documents_created_at ON documents(created_at DESC);

-- Learning Progress Table
CREATE TABLE learning_progress (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    topic VARCHAR2(255 CHAR) NOT NULL,
    roadmap JSON DEFAULT '{}',
    completed_items JSON DEFAULT '[]',
    current_level VARCHAR2(50 CHAR) DEFAULT 'beginner' CHECK (current_level IN ('beginner', 'intermediate', 'advanced')),
    notes CLOB,
    is_active NUMBER(1) DEFAULT 1,
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP,
    updated_at TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT learning_progress_is_active_bool CHECK (is_active IN (0, 1))
);

CREATE INDEX idx_learning_progress_user_id ON learning_progress(user_id);
CREATE INDEX idx_learning_progress_topic ON learning_progress(topic);

-- Triggers for updated_at
CREATE OR REPLACE TRIGGER update_users_updated_at
BEFORE UPDATE ON users
FOR EACH ROW
BEGIN
    :NEW.updated_at := SYSTIMESTAMP;
END;
/

CREATE OR REPLACE TRIGGER update_conversations_updated_at
BEFORE UPDATE ON conversations
FOR EACH ROW
BEGIN
    :NEW.updated_at := SYSTIMESTAMP;
END;
/

CREATE OR REPLACE TRIGGER update_documents_updated_at
BEFORE UPDATE ON documents
FOR EACH ROW
BEGIN
    :NEW.updated_at := SYSTIMESTAMP;
END;
/

CREATE OR REPLACE TRIGGER update_learning_progress_updated_at
BEFORE UPDATE ON learning_progress
FOR EACH ROW
BEGIN
    :NEW.updated_at := SYSTIMESTAMP;
END;
/

-- Sample Data (Optional - for testing)

-- Insert a test user (password is 'password123' hashed with bcrypt)
INSERT INTO users (email, username, hashed_password, full_name) VALUES
('test@example.com', 'testuser', '$2b$12$LQv3c1yqBWVHxkd0LHAkCOYz6TtxMQJqhN8/LewY5GyYqOqMgYQAK', 'Test User');

-- Comments for documentation
COMMENT ON TABLE users IS 'Stores user account information';
COMMENT ON TABLE conversations IS 'Stores chat conversation metadata';
COMMENT ON TABLE messages IS 'Stores individual chat messages';
COMMENT ON TABLE documents IS 'Stores uploaded document information';
COMMENT ON TABLE learning_progress IS 'Stores user learning progress and roadmaps';

-- Grant permissions (adjust username as needed)
GRANT ALL PRIVILEGES ON users TO nova_user;
GRANT ALL PRIVILEGES ON conversations TO nova_user;
GRANT ALL PRIVILEGES ON messages TO nova_user;
GRANT ALL PRIVILEGES ON documents TO nova_user;
GRANT ALL PRIVILEGES ON learning_progress TO nova_user;
