-- NOVA AI Storage Reference
-- Current persistence model: MongoDB
-- Runtime bootstrap: backend/config/database.py -> init_db() / _ensure_indexes()
--
-- This file is intentionally comment-only. The active backend no longer uses a
-- relational schema or SQLAlchemy migrations.
--
-- Collections
--
-- users
--   fields:
--     id
--     email
--     username
--     hashed_password
--     full_name
--     is_active
--     is_verified
--     created_at
--     updated_at
--   indexes:
--     unique(id)
--     unique(email)
--     unique(username)
--
-- conversations
--   fields:
--     id
--     user_id
--     title
--     legacy_messages
--     model
--     is_shared
--     share_id
--     share_title
--     shared_at
--     view_count
--     context_summary
--     context_summary_message_count
--     context_summary_updated_at
--     created_at
--     updated_at
--   indexes:
--     unique(id)
--     (user_id asc, updated_at desc)
--     unique(share_id) sparse
--
-- messages
--   fields:
--     id
--     conversation_id
--     role
--     content
--     meta
--     created_at
--   indexes:
--     unique(id)
--     (conversation_id asc, created_at asc)
--
-- documents
--   fields:
--     id
--     user_id
--     filename
--     file_path
--     file_type
--     file_size
--     text_content
--     summary
--     is_processed
--     created_at
--     updated_at
--   indexes:
--     unique(id)
--     (user_id asc, created_at desc)
--
-- learning_progress
--   fields:
--     id
--     user_id
--     topic
--     roadmap
--     completed_items
--     current_level
--     notes
--     is_active
--     created_at
--     updated_at
--   indexes:
--     unique(id)
--     (user_id asc, updated_at desc)
--
-- counters
--   purpose:
--     stores auto-increment values for Mongo-backed numeric ids on users,
--     messages, documents, and learning_progress
--
-- Notes
--
-- - Chat messages are deleted when their parent conversation is deleted.
-- - Document retrieval state is maintained by backend/services/vector_service.py.
-- - Collections and indexes are created automatically during backend startup.
